### ISSUE TITLE
Laravel 6.0

### ISSUE THREAD

**Issue by ValleyInforge** [foothing/laravel-simple-pageviews#5]
Any new version for laravel 6.0?

Thanks

**Comment by brazorf** [comment]
Not planned yet, might happen but not before Feb 2020 i'm sorry

**Comment by ValleyInforge** [comment]
I imported it in laravel 6.x with success (changed composer.json), very nice repo (it works)! Thanks!

**Comment by rickg123** [comment]
> I imported it in laravel 6.x with success (changed composer.json), very nice repo (it works)! Thanks!

What was your method for doing this?
